#!/bin/sh
#
# Copyright 2017 Cisco Systems Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -euo pipefail

# Note(NB):  Externally passed in environment variables are not in standard upper case, but I haven't changed them
# because they are referenced in other repos.
CMD=("netmaster")
if [ -n "${dbg_flag:-}" ]
then
    CMD+=("$dbg_flag")
fi
if [ -n "${plugin_name:-}" ]
then
    CMD+=("-plugin-name=$plugin_name")
fi
if [ -n "${plugin_mode:-}" ]
then
    CMD+=("-cluster-mode=$plugin_mode")
fi
if [ -n "${cluster_store:-}" ]
then
    CMD+=("-cluster-store=$cluster_store")
fi
if [ -n "${listen_url:-}" ]
then
    CMD+=("-listen-url=$listen_url")
fi
if [ -n "${control_url:-}" ]
then
    CMD+=("-control-url=$control_url")
fi

echo "Starting Contiv Netmaster (${CMD[@]})..."
exec "${CMD[@]}"
